/**
 * Year-Round Checklist (.xlsx).
 *
 * Ported from v12 genChecklist (_Templates/OAP Contest Setup.html, ~lines
 * 2185–2318). A plain (unstyled) value grid: a Done? / Task / Notes table whose
 * body is a FIXED nine-phase checklist (Upon Appointment → Post-Contest). The
 * PHASES data below is transcribed verbatim from v12 — task/note/sub row types
 * render with v12's exact prefixes (● for notes, "    → " for sub-items).
 *
 * Only the contest title is variable; everything else is constant reference text
 * — do not reword it. Data-validation dropdowns were intentionally omitted in
 * v12 (SheetJS CE cannot write them); users edit the Done? column directly.
 *
 * Pure: no DOM. Synchronous — XLSX.write packs the workbook directly.
 */

import * as XLSX from 'xlsx-js-style';
import { contestTitleLong, type Contest } from '../model/contest';
import { xlsxBuf } from './xlsx';

interface ChecklistItem {
  t: 'task' | 'note' | 'sub';
  text: string;
}
interface ChecklistPhase {
  label: string;
  timing: string;
  items: ChecklistItem[];
}

const PHASES: ChecklistPhase[] = [
  {
    label: 'PHASE 0 — Upon Appointment',
    timing: 'Complete immediately upon accepting the Contest Manager role.',
    items: [
      { t: 'task', text: 'Determine planning meeting status — has a meeting been held? If not, confirm one is scheduled (Aug 10–Nov 1).' },
      { t: 'note', text: 'Enrollment list is tentative until after October 1 — confirm final participating schools after that date.' },
    ],
  },
  {
    label: 'PHASE 1 — Summer Preparation',
    timing: 'BIDC adjudicators after July 15. District/Zone NOT before August 10.',
    items: [
      { t: 'task', text: 'BIDC: Begin contacting adjudicators after July 15' },
      { t: 'task', text: 'Verify facility is reserved for rehearsal and contest dates' },
      { t: 'note', text: 'Zone and District adjudicators may NOT be contacted before August 10.' },
    ],
  },
  {
    label: 'PHASE 2 — Fall Planning Meeting',
    timing: 'Planning meeting must occur Aug 10 – Nov 1.',
    items: [
      { t: 'task', text: 'Prepare Planning Meeting Agenda' },
      { t: 'task', text: 'Confirm contest site — reserve stage, dressing rooms, judge room, hospitality room' },
      { t: 'task', text: 'Set contest date and time — verify against UIL Official Calendar' },
      { t: 'task', text: 'Draw for performance order (blind draw; required annually at all levels)' },
      { t: 'task', text: 'Contact and contract adjudicator(s) through TTAO Connect' },
      { t: 'sub', text: 'Arrange payment — confirm procedure with Spring Meet Director' },
      { t: 'sub', text: 'Arrange hotel, travel, and meals per contract' },
      { t: 'task', text: 'Contact host school re: local rules for contest site' },
      { t: 'task', text: 'Send list of needed personnel/site crew roles to host school' },
      { t: 'task', text: 'Create a district contact list with all director names and emails' },
      { t: 'task', text: 'Verify light cue deadline for host school pre-programming' },
      { t: 'task', text: 'BIDC: Register meet on UIL Bi-District online form (by August 31)' },
    ],
  },
  {
    label: 'PHASE 3 — At Least 60 Days Before',
    timing: 'Complete these well before the pre-contest preparation sprint.',
    items: [
      { t: 'task', text: 'Build Contest Day Schedule (generated by this tool)' },
      { t: 'task', text: 'Build Rehearsal Schedule (generated by this tool)' },
      { t: 'task', text: 'Confirm adjudicator travel logistics: arrival, parking, private space, meals, payment' },
      { t: 'task', text: 'Send Google Form to judges to collect preferences (hotel, dietary, etc.)' },
    ],
  },
  {
    label: 'PHASE 4 — Pre-Contest Preparation',
    timing: 'Send Information Packet. Awards must be ordered/confirmed at least 10 days prior.',
    items: [
      { t: 'task', text: 'Send Information Packet to all participating schools' },
      { t: 'sub', text: 'Include: performance order, date/time, facility info, basic set available' },
      { t: 'sub', text: 'Include: rehearsal schedule, equipment to bring, entry fee info, local rules' },
      { t: 'sub', text: 'Include: unit set availability, adjudicator mailing addresses for script submission' },
      { t: 'task', text: 'Verify awards have been ordered/received' },
      { t: 'sub', text: 'District/BiDistrict: 3 Advancing, 1 Alternate, 2 Best Performers, All-Star Cast ×8, HM All-Star Cast ×8' },
      { t: 'task', text: "Prepare Director's Meeting Script/Agenda" },
      { t: 'task', text: 'Prepare Rehearsal Meeting Checklist' },
      { t: 'task', text: 'Prepare Timer Instructions Sheet and distribute to timekeepers' },
      { t: 'task', text: 'Prepare Awards Script' },
      { t: 'task', text: 'Verify Program with Host School' },
      { t: 'task', text: 'Distribute site crew job description sheets; confirm all roles filled' },
      { t: 'task', text: 'Prepare CM Supply Box: flashlight, tape (clear/spike/glow/gaff), scissors, folders, pens, pencils, markers, stopwatches, clipboards, wristbands' },
      { t: 'task', text: 'Verify light cue sheet collection process and deadline' },
      { t: 'task', text: 'Confirm dressing room assignments for each school' },
      { t: 'task', text: 'Confirm admission policy and pricing; arrange box office staffing' },
    ],
  },
  {
    label: 'PHASE 5 — Pre-Contest Week',
    timing: 'Final logistics and confirmations in the week before rehearsals and contest.',
    items: [
      { t: 'task', text: 'Send reminder communication to all directors (include schedule)' },
      { t: 'task', text: 'Assign spike tape colors to each school; document assignments' },
      { t: 'task', text: 'Confirm entry fees collected and payment ready for adjudicators' },
      { t: 'task', text: 'Final site crew check-in — confirm all roles covered' },
      { t: 'task', text: "Confirm box locations staked/taped on stage for each school's set storage" },
      { t: 'task', text: 'Confirm backstage supplies in place: broom, trash cans, stage weights, backstage lights' },
      { t: 'task', text: 'Confirm unit set is in place (door, window, French doors)' },
      { t: 'task', text: 'Confirm judge/CM area is set up in house (table, chairs, electricity, pens)' },
      { t: 'task', text: 'Finalize and print programs, schedules, and all contest-day paperwork' },
    ],
  },
  {
    label: 'PHASE 6 — Rehearsal Day(s)',
    timing: 'Directors must arrive at least 20 minutes before their scheduled rehearsal time.',
    items: [
      { t: 'task', text: 'Set up stage, loading dock, dressing rooms, and judge/hospitality rooms' },
      { t: 'task', text: 'Brief site crew before first rehearsal' },
      { t: 'task', text: 'For each school: conduct pre-rehearsal meeting and verify all paperwork' },
      { t: 'sub', text: 'Evidence of royalty payment (or public domain status)' },
      { t: 'sub', text: "Publisher's approval to produce (for scenes from long plays)" },
      { t: 'sub', text: 'Written UIL OAP approval (if play not on approved list)' },
      { t: 'sub', text: 'Signed Community Standards & Copyright Compliance Form' },
      { t: 'sub', text: 'Music Log (required if using music)' },
      { t: 'sub', text: 'Integrity Script (must be present at rehearsal)' },
      { t: 'sub', text: 'Entry fee payment (if applicable)' },
      { t: 'note', text: 'School may NOT begin rehearsal without all required paperwork AND entry fee.' },
      { t: 'task', text: 'Conduct Rehearsal Meeting with each school' },
      { t: 'task', text: 'Require Full Technical Disclosure: all set pieces, props, questionable blocking shown' },
      { t: 'task', text: "Confirm each school's spike tape color and set storage box location" },
      { t: 'note', text: 'Alternates may assist with spiking and observe from audience. NOT backstage during official rehearsal.' },
    ],
  },
  {
    label: 'PHASE 7 — Contest Day',
    timing: 'See also: Contest Day Checklist (separate document).',
    items: [
      { t: 'task', text: 'Early setup: CM station, judge area, hospitality room' },
      { t: 'task', text: 'Confirm timekeepers are in place; review time warning procedures one final time' },
      { t: 'task', text: 'Confirm all school set boxes are in place; stage is ready' },
      { t: 'task', text: 'Distribute wristbands/tickets to school personnel; open box office' },
      { t: 'task', text: "Conduct Director's Meeting" },
      { t: 'sub', text: 'Introductions: adjudicators, directors, timekeepers' },
      { t: 'sub', text: 'Review opening/closing cues, critique format, timing procedures' },
      { t: 'sub', text: 'Confirm dressing room policy; alternate status; disability disclosures' },
      { t: 'task', text: 'For each performance: give 15-min warning to next company; oversee setup' },
      { t: 'task', text: 'After each performance: oversee strike; conduct critique (if after-each format)' },
      { t: 'task', text: 'After all performances: conduct critiques (if all-shows-first format)' },
      { t: 'task', text: 'Conduct Awards Ceremony' },
      { t: 'task', text: 'Confirm all companies have fully struck and cleared stage before awards' },
    ],
  },
  {
    label: 'PHASE 8 — Post-Contest',
    timing: 'Complete as soon as possible after the contest.',
    items: [
      { t: 'task', text: 'Submit official results to UIL / Spring Meet Director' },
      { t: 'task', text: 'Send Advancing Schools Letter to each advancing company' },
      { t: 'task', text: 'Send thank-you to adjudicators and link the evaluation form' },
      { t: 'task', text: 'Send thank-you to host school administration and technical staff' },
      { t: 'task', text: 'BIDC: Coordinate advancing school information with partner district' },
      { t: 'task', text: 'Archive all templates used this year; note any updates needed before next cycle' },
    ],
  },
];

export function buildChecklist(contest: Contest): Uint8Array {
  const rows: string[][] = [];
  const merges: XLSX.Range[] = [];
  let ri = 0;
  rows.push([contestTitleLong(contest.identity)]);
  merges.push({ s: { r: ri, c: 0 }, e: { r: ri, c: 2 } });
  ri++;
  rows.push(['UIL OAP Contest Manager — Year-Round Checklist']);
  merges.push({ s: { r: ri, c: 0 }, e: { r: ri, c: 2 } });
  ri++;
  rows.push([]);
  ri++;
  rows.push(['Done?', 'Task', 'Notes']);
  ri++;
  PHASES.forEach((phase) => {
    rows.push([phase.label, '', phase.timing || '']);
    merges.push({ s: { r: ri, c: 0 }, e: { r: ri, c: 1 } });
    ri++;
    phase.items.forEach((item) => {
      if (item.t === 'note') rows.push(['', '● ' + item.text, '']);
      else if (item.t === 'sub') rows.push(['', '    → ' + item.text, '']);
      else rows.push(['', item.text, '']);
      ri++;
    });
    rows.push([]);
    ri++;
  });
  // Future features note
  rows.push(['']);
  ri++;
  rows.push(['', 'Optional Future Features:', '']);
  ri++;
  rows.push(['', '  • Auto-populate school/director info from previous years', '']);
  ri++;
  rows.push(['', '  • Persistent web version with save-to-local-file (check/uncheck tasks)', '']);
  ri++;
  rows.push(['', '  • Add custom tasks as needed', '']);
  ri++;

  const wb = XLSX.utils.book_new();
  const ws = XLSX.utils.aoa_to_sheet(rows);
  ws['!cols'] = [{ wch: 9 }, { wch: 80 }, { wch: 52 }];
  ws['!merges'] = merges;
  XLSX.utils.book_append_sheet(wb, ws, 'Year-Round Checklist');
  return xlsxBuf(wb);
}
